config: !!python/object:netisg.config.ModelConfig
  feature_vector_size: 256
  gat_heads: 4
  gat_hidden_channels: 64
  gat_in_channels: 3
  in_channels: 4
  initial_features: 16
  sdf_hidden_dim: 256
train_config: !!python/object:netisg.config.TrainerConfig
  batch_size: 4
  checkpoint_dir: experiments/
  experiment_name: netisg_v7_run
  image_size: 256
  learning_rate: 0.0001
  max_epochs: 50
  num_workers: 2
